### ISSUE TITLE
(null): Library not found for -lPods-Screentendo-GPUImage

### ISSUE THREAD

**Issue by 4fthawaiian** [AaronRandall/Screentendo#2]
Refuses to build in XCode. 

```
Ld /Users/bradleymccrorey/Library/Developer/Xcode/DerivedData/Screentendo-gjhesuoishnetnfpgpijgaijepvb/Build/Products/Debug/Screentendo.app/Contents/MacOS/Screentendo normal x86_64
    cd /Users/bradleymccrorey/Downloads/Screentendo-master
    export MACOSX_DEPLOYMENT_TARGET=10.10
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -L/Users/bradleymccrorey/Library/Developer/Xcode/DerivedData/Screentendo-gjhesuoishnetnfpgpijgaijepvb/Build/Products/Debug -F/Users/bradleymccrorey/Library/Developer/Xcode/DerivedData/Screentendo-gjhesuoishnetnfpgpijgaijepvb/Build/Products/Debug -filelist /Users/bradleymccrorey/Library/Developer/Xcode/DerivedData/Screentendo-gjhesuoishnetnfpgpijgaijepvb/Build/Intermediates/Screentendo.build/Debug/Screentendo.build/Objects-normal/x86_64/Screentendo.LinkFileList -Xlinker -rpath -Xlinker @executable_path/../Frameworks -mmacosx-version-min=10.10 -ObjC -lPods-Screentendo-GPUImage -fobjc-arc -fobjc-link-runtime -lPods-Screentendo -Xlinker -dependency_info -Xlinker /Users/bradleymccrorey/Library/Developer/Xcode/DerivedData/Screentendo-gjhesuoishnetnfpgpijgaijepvb/Build/Intermediates/Screentendo.build/Debug/Screentendo.build/Objects-normal/x86_64/Screentendo_dependency_info.dat -o /Users/bradleymccrorey/Library/Developer/Xcode/DerivedData/Screentendo-gjhesuoishnetnfpgpijgaijepvb/Build/Products/Debug/Screentendo.app/Contents/MacOS/Screentendo

ld: library not found for -lPods-Screentendo-GPUImage
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jasarien** [comment]
Did you read the readme? The project requires external libraries which are managed with cocoapods. Install cocoapods and run `pod install`.

**Comment by 4fthawaiian** [comment]
Yep! definitely did that first:

```
Bradleys-MacBook-Air:Screentendo-master bradleymccrorey$ pod install
[!] Unable to load a specification for the plugin `/opt/homebrew-cask/Caskroom/cocoapods/0.37.0/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-plugins-install-0.0.1`
Analyzing dependencies

CocoaPods 0.37.1 is available.
To update use: `sudo gem install cocoapods`

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Using GPUImage (0.1.6)
Generating Pods project
Integrating client project
Bradleys-MacBook-Air:Screentendo-master bradleymccrorey$
```

**Comment by 4fthawaiian** [comment]
I'm in the progress of updating cocoapods, as the message above suggests. We'll see if that has any effect. ¯_(ツ)_/¯

**Comment by 4fthawaiian** [comment]
sadly, no effect:

```
Ld /Users/bradleymccrorey/Library/Developer/Xcode/DerivedData/Screentendo-gjhesuoishnetnfpgpijgaijepvb/Build/Products/Debug/Screentendo.app/Contents/MacOS/Screentendo normal x86_64
    cd /Users/bradleymccrorey/Downloads/Screentendo-master
    export MACOSX_DEPLOYMENT_TARGET=10.10
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -L/Users/bradleymccrorey/Library/Developer/Xcode/DerivedData/Screentendo-gjhesuoishnetnfpgpijgaijepvb/Build/Products/Debug -F/Users/bradleymccrorey/Library/Developer/Xcode/DerivedData/Screentendo-gjhesuoishnetnfpgpijgaijepvb/Build/Products/Debug -filelist /Users/bradleymccrorey/Library/Developer/Xcode/DerivedData/Screentendo-gjhesuoishnetnfpgpijgaijepvb/Build/Intermediates/Screentendo.build/Debug/Screentendo.build/Objects-normal/x86_64/Screentendo.LinkFileList -Xlinker -rpath -Xlinker @executable_path/../Frameworks -mmacosx-version-min=10.10 -ObjC -lPods-Screentendo-GPUImage -fobjc-arc -fobjc-link-runtime -lPods-Screentendo -Xlinker -dependency_info -Xlinker /Users/bradleymccrorey/Library/Developer/Xcode/DerivedData/Screentendo-gjhesuoishnetnfpgpijgaijepvb/Build/Intermediates/Screentendo.build/Debug/Screentendo.build/Objects-normal/x86_64/Screentendo_dependency_info.dat -o /Users/bradleymccrorey/Library/Developer/Xcode/DerivedData/Screentendo-gjhesuoishnetnfpgpijgaijepvb/Build/Products/Debug/Screentendo.app/Contents/MacOS/Screentendo

ld: library not found for -lPods-Screentendo-GPUImage
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by josephhsieh** [comment]
I got the same error as well....

**Comment by josephhsieh** [comment]
my bad.. actually you have to run the cocoapod project, not Xcode project.
type this in your Terminal: open Screentendo.xcworkspace

**Comment by AaronRandall** [comment]
@4fthawaiian did @josephhsieh's suggestion work for you, or are you still having issues with this?

Thanks

**Comment by 4fthawaiian** [comment]
Well, I haven't had a chance yet, as that was 2am my time. I'll have a go
and get back to you. :P
On Thu, May 28, 2015 at 8:37 AM Aaron Randall notifications@github.com
wrote:

> @4fthawaiian https://github.com/4fthawaiian did @josephhsieh
> https://github.com/josephhsieh's suggestion work for you, or are you
> still having issues with this?
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AaronRandall/Screentendo/issues/2#issuecomment-106313466
> .
> 
> This e-mail message may contain confidential or legally privileged
> information and is intended only for the use of the intended recipient(s).
> Any unauthorized disclosure, dissemination, distribution, copying or the
> taking of any action in reliance on the information herein is prohibited.
> E-mails are not secure and cannot be guaranteed to be error free as they
> can be intercepted, amended, or contain viruses. Anyone who communicates
> with us by e-mail is deemed to have accepted these risks. Pixel Press
> Technology, LLC is not responsible for errors or omissions in this message
> and denies any responsibility for any damage arising from the use of
> e-mail. Any opinion and other statement contained in this message and any
> attachment are solely those of the author and do not necessarily represent
> those of the company.

## 

This e-mail message may contain confidential or legally privileged 
information and is intended only for the use of the intended recipient(s). 
Any unauthorized disclosure, dissemination, distribution, copying or the 
taking of any action in reliance on the information herein is prohibited. 
E-mails are not secure and cannot be guaranteed to be error free as they 
can be intercepted, amended, or contain viruses. Anyone who communicates 
with us by e-mail is deemed to have accepted these risks. Pixel Press 
Technology, LLC is not responsible for errors or omissions in this message 
and denies any responsibility for any damage arising from the use of 
e-mail. Any opinion and other statement contained in this message and any 
attachment are solely those of the author and do not necessarily represent 
those of the company.

**Comment by 4fthawaiian** [comment]
👍 looks good. Thanks all!

**Comment by humza-ios** [comment]
Need to add $(inherited) in Other Linker Flag. For me Issue is resolved .
