### ISSUE TITLE
Not working in OS X El Capitan.

### ISSUE THREAD

**Issue by jiegec** [AaronRandall/Screentendo#5]
Even updated to GPUImage v0.1.7, still not working. 

![image](https://cloud.githubusercontent.com/assets/6127678/10563309/03e24510-75b8-11e5-9091-718f2c167429.png)

By the way, the .gitignore is not enough. Try https://github.com/github/gitignore/blob/master/Global/Xcode.gitignore.

**Comment by jiegec** [comment]
Any progress?

**Comment by liyezhou** [comment]
Same here!
